# netlify.toml

# netlify.toml
[build]
  command = "npm run build"
  publish = "build"

[dev]
  command   = "npm start"
  port      = 3000
  framework = "#create-react-app"


# Optional: environment you want locked (e.g. Node 20.x via .nvmrc)
[build.environment]
  NODE_VERSION = "20"

# Deploy previews and production share the same build settings,
# but you can override per context if needed:
# [context.production.environment]
#   NODE_ENV = "production"
