# netlify.toml

[build]
  # Runs your Vite production build
  command   = "npm run build"
  # Directory to deploy
  publish   = "dist"
  # If your code is in a subfolder, specify it here:
  # base    = "path/to/subfolder"

# Optional: settings for Netlify Dev (local testing)
[dev]
  command   = "npm run dev"
  port      = 5173
  framework = "#custom"

# Optional: environment you want locked (e.g. Node 20.x via .nvmrc)
[build.environment]
  NODE_VERSION = "20"

# Deploy previews and production share the same build settings,
# but you can override per context if needed:
# [context.production.environment]
#   NODE_ENV = "production"
